---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/mine_sweeper/start_game":
    post:
      summary: start_game mine_sweeper
      responses:
        '200':
          description: successful
  "/api/v1/mine_sweeper/set_position/{game_state_id}":
    parameters:
    - name: game_state_id
      in: path
      description: game_state_id
      required: true
      schema:
        type: string
    post:
      summary: set_position mine_sweeper
      responses:
        '200':
          description: successful
  "/api/v1/mine_sweeper/toggle_flag/{game_state_id}":
    parameters:
    - name: game_state_id
      in: path
      description: game_state_id
      required: true
      schema:
        type: string
    post:
      summary: toggle_flag mine_sweeper
      responses:
        '200':
          description: successful
  "/api/v1/mine_sweeper/game_board/{game_state_id}":
    parameters:
    - name: game_state_id
      in: path
      description: game_state_id
      required: true
      schema:
        type: string
    get:
      summary: game_board mine_sweeper
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
