---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/mine_sweeper/start_game":
    post:
      summary: start_game mine_sweeper
      tags:
      - Start Game
      parameters: []
      responses:
        '200':
          description: Game started
          content:
            application/json:
              examples:
                Game started:
                  value:
                    id: 1
                    start_time: '2023-05-24T07:40:30.980Z'
                    state: playing
                    face: "\U0001F600"
                    board:
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
        '400':
          description: Error
          content:
            application/json:
              examples:
                zero mines:
                  value:
                    error: zero_mines
                zero height:
                  value:
                    error: zero_height
                zero width:
                  value:
                    error: zero_width
                invalid mine count:
                  value:
                    error: invalid_mine_count
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                height:
                  type: integer
                width:
                  type: integer
                mines:
                  type: integer
              required:
              - height
              - width
              - mines
              example:
                height: 8
                width: 8
                mines: 10
  "/api/v1/mine_sweeper/set_position/{game_state_id}":
    parameters:
    - name: game_state_id
      in: path
      description: game_state_id
      required: true
      schema:
        type: string
    patch:
      summary: set_position mine_sweeper
      tags:
      - Set new position
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                Discover a common cell:
                  value:
                    id: 1
                    start_time: '2023-05-24T07:40:31.039Z'
                    state: playing
                    face: "\U0001F600"
                    board:
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - '1'
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                Game over:
                  value:
                    id: 1
                    start_time: '2023-05-24T07:40:31.080Z'
                    state: lost
                    face: "\U0001F635"
                    board:
                    - - "\U0001F4A3"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F4A3"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F4A3"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
        '400':
          description: Error
          content:
            application/json:
              examples:
                Invalid position:
                  value:
                    error: invalid_position
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                position:
                  x:
                    type: integer
                  y:
                    type: integer
              required:
              - position
              example:
                position:
                  x: 0
                  y: 1
  "/api/v1/mine_sweeper/toggle_flag/{game_state_id}":
    parameters:
    - name: game_state_id
      in: path
      description: game_state_id
      required: true
      schema:
        type: string
    patch:
      summary: toggle_flag mine_sweeper
      tags:
      - Add or remove flag
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                Set Flag:
                  value:
                    id: 1
                    start_time: '2023-05-24T07:40:31.165Z'
                    state: playing
                    face: "\U0001F600"
                    board:
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F6A9"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
        '400':
          description: Error
          content:
            application/json:
              examples:
                Invalid position to set flag:
                  value:
                    error: invalid_position
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                position:
                  x:
                    type: integer
                  y:
                    type: integer
              required:
              - position
              example:
                position:
                  x: 0
                  y: 7
  "/api/v1/mine_sweeper/game_board/{game_state_id}":
    parameters:
    - name: game_state_id
      in: path
      description: game_state_id
      required: true
      schema:
        type: string
    get:
      summary: game_board mine_sweeper
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                Find game:
                  value:
                    id: 1
                    start_time: '2023-05-24T07:40:31.278Z'
                    state: playing
                    face: "\U0001F600"
                    board:
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                    - - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
                      - "\U0001F7EA"
        '400':
          description: Error
          content:
            application/json:
              examples:
                Game not found:
                  value:
                    error: Couldn't find GameState with 'id'=1000
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: minesweeper-trial.herokuapp.com
